### ISSUE TITLE
Address Labels struct

### ISSUE THREAD

**Issue by rjcortese** [kodemartin/rustpostal#4]
Hello! Thanks for putting this crate together.
I think it would be helpful to have a struct for the parse result... maybe something like:

`pub struct ParseResult {
    house: Option<String>,
    house_number: Option<String>,
    ...
}`

That way could use that struct for typing in other crates.
What do you think?

[The list of labels](https://github.com/openvenues/libpostal/blob/master/src/address_parser.h#L106-L125)

**Comment by kodemartin** [comment]
> Hello! Thanks for putting this crate together. I think it would be helpful to have a struct for the parse result... maybe something like:
> 
> `pub struct ParseResult { house: Option<String>, house_number: Option<String>, ... }`
> 
> That way could use that struct for typing in other crates. What do you think?
> 
> [The list of labels](https://github.com/openvenues/libpostal/blob/master/src/address_parser.h#L106-L125)

Hi @rjcortese! I am glad you find this useful.

What you propose can be indeed a helpful feature for encapsulating the result components. Here are my remarks:

* I would suggest using a name that doesn't contain `Result`, since this is typically reserved for the well-known `enum` values in Rust. Could be simply `ParsedAddress`.
* The only downside I see is maintaining the `Struct` fields to be in sync with the C-library. But I guess we can expect little if any breaking changes to this respect in the upstream.
* How would you go about and implement it? The way I see it a simple `From AddressParserResponse for ParsedAddress` implementation would do.
